
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:6 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Wersja programu MSBuild 17.7.2+d6990bcfa dla .NET Framework
      Kompilacja rozpoczęła się 15.01.2024 11:06:55.
      
      Projekt "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.vcxproj" w węźle 1 (domyślne elementy docelowe).
      PrepareForBuild:
        Tworzenie katalogu "Debug\\".
        Tworzenie katalogu "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Trwa tworzenie "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", ponieważ określono "AlwaysCreate".
        Modyfikowanie "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Usuwanie pliku "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Modyfikowanie "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Kompilowanie projektu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdC\\CompilerIdC.vcxproj" wykonane (domyślne elementy docelowe).
      
      Kompilacja powiodła się.
          Ostrzeżenia: 0
          Liczba błędów: 0
      
      Czas, który upłynął: 00:00:02.25
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/3.28.0-rc1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:6 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Wersja programu MSBuild 17.7.2+d6990bcfa dla .NET Framework
      Kompilacja rozpoczęła się 15.01.2024 11:06:58.
      
      Projekt "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" w węźle 1 (domyślne elementy docelowe).
      PrepareForBuild:
        Tworzenie katalogu "Debug\\".
        Tworzenie katalogu "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Trwa tworzenie "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", ponieważ określono "AlwaysCreate".
        Modyfikowanie "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Usuwanie pliku "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Modyfikowanie "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Kompilowanie projektu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\3.28.0-rc1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" wykonane (domyślne elementy docelowe).
      
      Kompilacja powiodła się.
          Ostrzeżenia: 0
          Liczba błędów: 0
      
      Czas, który upłynął: 00:00:01.79
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/3.28.0-rc1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-gcu1yz"
      binary: "C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-gcu1yz"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-gcu1yz'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_d6219.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Wersja programu MSBuild 17.7.2+d6990bcfa dla .NET Framework
        Kompilacja rozpoczęła się 15.01.2024 11:07:01.
        
        Projekt "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-gcu1yz\\cmTC_d6219.vcxproj" w węźle 1 (domyślne elementy docelowe).
        PrepareForBuild:
          Tworzenie katalogu "cmTC_d6219.dir\\Debug\\".
          Tworzenie katalogu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-gcu1yz\\Debug\\".
          Tworzenie katalogu "cmTC_d6219.dir\\Debug\\cmTC_d6219.tlog\\".
        InitializeBuildStatus:
          Trwa tworzenie "cmTC_d6219.dir\\Debug\\cmTC_d6219.tlog\\unsuccessfulbuild", ponieważ określono "AlwaysCreate".
          Modyfikowanie "cmTC_d6219.dir\\Debug\\cmTC_d6219.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d6219.dir\\Debug\\\\" /Fd"cmTC_d6219.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\michl\\Downloads\\cmake-3.28.0-rc1-windows-x86_64\\cmake-3.28.0-rc1-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ wersja kompilatora optymalizującego 19.37.32826.1 dla x64
          Copyright (C) Microsoft Corporation. Wszystkie prawa zastrzeżone.
          CMakeCCompilerABI.c
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_d6219.dir\\Debug\\\\" /Fd"cmTC_d6219.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Users\\michl\\Downloads\\cmake-3.28.0-rc1-windows-x86_64\\cmake-3.28.0-rc1-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-gcu1yz\\Debug\\cmTC_d6219.exe" /INCREMENTAL /ILK:"cmTC_d6219.dir\\Debug\\cmTC_d6219.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-gcu1yz/Debug/cmTC_d6219.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-gcu1yz/Debug/cmTC_d6219.lib" /MACHINE:X64  /machine:x64 cmTC_d6219.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_d6219.vcxproj -> C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-gcu1yz\\Debug\\cmTC_d6219.exe
        FinalizeBuildStatus:
          Usuwanie pliku "cmTC_d6219.dir\\Debug\\cmTC_d6219.tlog\\unsuccessfulbuild".
          Modyfikowanie "cmTC_d6219.dir\\Debug\\cmTC_d6219.tlog\\cmTC_d6219.lastbuildstate".
        Kompilowanie projektu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-gcu1yz\\cmTC_d6219.vcxproj" wykonane (domyślne elementy docelowe).
        
        Kompilacja powiodła się.
            Ostrzeżenia: 0
            Liczba błędów: 0
        
        Czas, który upłynął: 00:00:02.19
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Users/michl/Downloads/cmake-3.28.0-rc1-windows-x86_64/cmake-3.28.0-rc1-windows-x86_64/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:6 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-ouyckq"
      binary: "C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-ouyckq"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-ouyckq'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_0b17e.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        Wersja programu MSBuild 17.7.2+d6990bcfa dla .NET Framework
        Kompilacja rozpoczęła się 15.01.2024 11:07:05.
        
        Projekt "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-ouyckq\\cmTC_0b17e.vcxproj" w węźle 1 (domyślne elementy docelowe).
        PrepareForBuild:
          Tworzenie katalogu "cmTC_0b17e.dir\\Debug\\".
          Tworzenie katalogu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-ouyckq\\Debug\\".
          Tworzenie katalogu "cmTC_0b17e.dir\\Debug\\cmTC_0b17e.tlog\\".
        InitializeBuildStatus:
          Trwa tworzenie "cmTC_0b17e.dir\\Debug\\cmTC_0b17e.tlog\\unsuccessfulbuild", ponieważ określono "AlwaysCreate".
          Modyfikowanie "cmTC_0b17e.dir\\Debug\\cmTC_0b17e.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0b17e.dir\\Debug\\\\" /Fd"cmTC_0b17e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\michl\\Downloads\\cmake-3.28.0-rc1-windows-x86_64\\cmake-3.28.0-rc1-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Microsoft (R) C/C++ wersja kompilatora optymalizującego 19.37.32826.1 dla x64
          Copyright (C) Microsoft Corporation. Wszystkie prawa zastrzeżone.
          CMakeCXXCompilerABI.cpp
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_0b17e.dir\\Debug\\\\" /Fd"cmTC_0b17e.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Users\\michl\\Downloads\\cmake-3.28.0-rc1-windows-x86_64\\cmake-3.28.0-rc1-windows-x86_64\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.37.32822\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-ouyckq\\Debug\\cmTC_0b17e.exe" /INCREMENTAL /ILK:"cmTC_0b17e.dir\\Debug\\cmTC_0b17e.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-ouyckq/Debug/cmTC_0b17e.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/michl/Documents/JPO/ProjektKalkulator/build_win/CMakeFiles/CMakeScratch/TryCompile-ouyckq/Debug/cmTC_0b17e.lib" /MACHINE:X64  /machine:x64 cmTC_0b17e.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_0b17e.vcxproj -> C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-ouyckq\\Debug\\cmTC_0b17e.exe
        FinalizeBuildStatus:
          Usuwanie pliku "cmTC_0b17e.dir\\Debug\\cmTC_0b17e.tlog\\unsuccessfulbuild".
          Modyfikowanie "cmTC_0b17e.dir\\Debug\\cmTC_0b17e.tlog\\cmTC_0b17e.lastbuildstate".
        Kompilowanie projektu "C:\\Users\\michl\\Documents\\JPO\\ProjektKalkulator\\build_win\\CMakeFiles\\CMakeScratch\\TryCompile-ouyckq\\cmTC_0b17e.vcxproj" wykonane (domyślne elementy docelowe).
        
        Kompilacja powiodła się.
            Ostrzeżenia: 0
            Liczba błędów: 0
        
        Czas, który upłynął: 00:00:01.81
        
      exitCode: 0
...
